import type { Metadata, Viewport } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";
import StructuredData from "./components/structured-data";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ovo",
});

const SITE_URL = "https://portfolio.paradon.work";
const SITE_NAME = "Paradon Thonthong";
const TITLE = "Paradon Thonthong — Full Stack Developer Portfolio";
const DESCRIPTION =
  "Paradon Thonthong (พรดล ทอนทอง) — Full Stack Developer from Thailand specializing in Next.js, Angular, Spring Boot and MySQL. View projects, services and get in touch.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s — Paradon Thonthong",
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  generator: "Next.js",
  referrer: "origin-when-cross-origin",
  keywords: [
    "Paradon Thonthong",
    "ภราดร ทนทอง",
    "Paradon",
    "Full Stack Developer",
    "Web Developer Thailand",
    "Next.js Developer",
    "Angular Developer",
    "Spring Boot Developer",
    "MySQL",
    "TypeScript",
    "Portfolio",
    "Thailand Developer",
    "Hire Full Stack Developer",
  ],
  category: "technology",
  // Drop your verification codes here after registering on each platform.
  // Google Search Console: https://search.google.com/search-console
  // Bing Webmaster Tools: https://www.bing.com/webmasters
  verification: {
    google: "REPLACE_WITH_GOOGLE_VERIFICATION_CODE",
    other: {
      "msvalidate.01": "REPLACE_WITH_BING_VERIFICATION_CODE",
    },
  },
  authors: [{ name: "Paradon Thonthong", url: SITE_URL }],
  creator: "Paradon Thonthong",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    // OG image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // Twitter image is auto-generated by app/opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#11001F" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Runs BEFORE React hydrates so the correct theme class is on <html>
  // from the very first paint. Avoids the white-flash on dark-mode reload.
  const themeInitScript = `
    (function(){
      try {
        var stored = localStorage.getItem('theme');
        var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        var dark = stored === 'dark' || (stored === null && prefersDark);
        if (dark) document.documentElement.classList.add('dark');
      } catch(e) {}
    })();
  `;

  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        <StructuredData />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${outfit.variable} ${ovo.variable} antialiased leading-8 overflow-x-hidden dark:bg-dark-theme dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
